# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout weapia-minigame
      uses: actions/checkout@v2
      with:
        path: weapia-minigame
        ref: develop
    - name: Checkout weapia-main
      uses: actions/checkout@v2
      with:
        repository: dig/weapia-main
        path: weapia-main
        ref: develop
        token: ${{ secrets.WEAPIA_PAT }}
    - name: Output test 1
      run: ls
    - name: Move into weapia-minigame
      run: cd weapia-minigame
    - name: Output test 2
      run: ls
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload built jars
      uses: actions/upload-artifact@v2
      with:
        name: jars
        path: bin/*.jar
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Download built jars
      uses: actions/download-artifact@v2
      with:
        name: jars
    - name: Create directory
      run: |
        mkdir -p ~/static/instance000a/plugins/
    - name: Move jars
      run: |
        mv bin/icerunner-1.0-SNAPSHOT.jar ~/static/instance000a/plugins
    - name: Restart servers
      run: |
        tmux send-keys -t instance000a "stop" ENTER